id: PDCB8CAB0
initial_creation_type: input
source_metadata:
  title: Kashmiri Śākyaśrībhadra
  language: bo
  description: 'Texts by and about the Kashmiri master Śākyaśrībhadra (shā kya shrī
    bzang po, 1127–1225), who in 1204 travelled to Tibet, where he became the teacher
    of a number of important lamas, including Sakya Paṇḍita Kunga Gyaltsen:'
  volume:
    d22435489f5440c7aa2fbef70dbea75f:
      title: An Instruction on Pure View and Conduct
      parent: Instructions
    bdf289b47aaf47a3bd10aac592aeb547:
      title: A Brief Practice for Paying Homage and Making Offerings to the Buddha
        together with his retinue of Arhats
      parent: Practices
    4634318b1cbb41d8b75e0a88f273957e:
      title: Taking the Vows of Sojong
      parent: Practices
    d86876a1c94a48eaad0ad3f8993a85b7:
      title: The Seven Branches for Practising the Sacred Dharma
      parent: Practices
    36e16255f51b4d118b9495930fd16f31:
      title: Verses of Refuge and Bodhicitta
      parent: Practices
created_at: '2022-03-01T02:21:09.311752'
last_modified_at: '2022-03-01T02:21:09.311754'
